### ISSUE TITLE
Calling a PHP class method from JavaScript

### ISSUE THREAD

**Issue by smebberson** [apioo/psx-v8#1]
Hey there. We're investigating using php-v8 and your helper library looked like it would help a great deal :)

However, I don't seem to be able to execute a PHP class method from JavaScript?

```
<?php

class Bing {
    function output_name() {
        return "Bing.out";
    }
}

$script = <<<JS

var message = 'Hello ' + console.foo;

resp = {
    message: console.log(message),
    bar: function(data){
        return 'Foo --' + bing.output_name() + '-- ' + data;
    },
    foo: 'bar'
};

JS;

$environment = new \PSX\V8\Environment();

$environment->set('bing', new Bing());
$environment->set('console', [
    'foo' => 'foo',
    'log' => function($value){
         return $value . ' and bar';
    }
]);

$environment->run($script);

$resp = $environment->get('resp');

echo $resp->get('message') . "\n"; // Hello foo and bar
echo $resp->get('bar')(['test']) . "\n"; // Foo test
echo $resp->get('foo') . "\n"; // bar
```

I get the following output:

```
Fatal error: Uncaught V8\Exceptions\TryCatchException: TypeError: Cannot read property 'output_name' of null in /src/public/vendor/psx-v8/src/Wrapper/FunctionWrapper.php:53 Stack trace: #0 /src/public/vendor/psx-v8/src/Wrapper/FunctionWrapper.php(53): V8\FunctionObject->Call(Object(V8\Context), Object(V8\ObjectValue), Array) #1 /src/public/web/v8.php(47): PSX\V8\Wrapper\FunctionWrapper->__invoke(Array) #2 {main} thrown in /src/public/vendor/psx-v8/src/Wrapper/FunctionWrapper.php on line 53
```

In fact, to get this to work, I had to update [L79 of `Encoder.php`](https://github.com/apioo/psx-v8/blob/master/src/Encoder.php#L79) to `} elseif ($value instanceof \stdClass || (is_array($value) && self::isAssoc($value))) {`.

**Comment by chriskapp** [comment]
Hi, great to hear that it helps. So at the moment the library was not designed to pass classes to the environment (except for \stdClass which becomes a javascript object). In your code `bing.output_name()` will probably return null. It handles only Closures which you can call. But your fix is useful since the isAssoc method accepts only arrays. If you like and have time you could create a pull request otherwise I can also simply commit the fix.

**Comment by smebberson** [comment]
@k42b3, I can do a PR for that simple fix. What sort of work is involved in getting it to work with classes?

**Comment by chriskapp** [comment]
Great ok I have merged the pull request. So Iam currently working on support for objects. Basically the idea is to add a new ObjectInterface which must be implemented by each class. The interface could look like this:

``` php
interface ObjectInterface
{
    public function getProperties();
}
```

And each class which wants to expose methods in JS needs to implement it i.e.:

``` php
class Foo implements ObjectInterface
{
    public function someMethod()
    {
    }

    public function getProperties()
    {
        return [
            'someMethod' => [$this, 'someMethod']
        ];
    }
}
```

In the `Encoder::encode` we can add a new `elseif` which checks for this interface and basically we only have to write: `return self::encode($value->getProperties());`. This approach is super flexible i.e. we could use `Reflection` to implement the method or the properties could come from an database etc. Then you could add those objects to the environment: `$environment->set('foo', new Foo());`.

**Comment by smebberson** [comment]
@k42b3, that seems like a nice extendable approach. We have a few classes in which we use `__call` to support dynamic functions. Would your approach support this use case?

**Comment by chriskapp** [comment]
@smebberson yes, these classes dont even need to implement the interface, they would work like a closure so you can add them directly to the environment.

**Comment by smebberson** [comment]
@k42b3, great. Please let me know if there is anything I can do to help.

**Comment by chriskapp** [comment]
Hi, fyi I have commited the `ObjectInterface`. Next I want to add more tests
to solidify the API. So feel free to test the solution for your use case.

**Comment by smebberson** [comment]
@k42b3, awesome. We'll have a play!

**Comment by smebberson** [comment]
@k42b3, thanks for adding `ObjectInterface`. It has certainly gotten us closer to our use case. I've copied below a more concrete example:

```
<?php

// Execute our JavaScript code within php-v8.
function execJS($script, $instance) {

    $environment = new \PSX\V8\Environment();
    $environment->set('fooInstance', new \PSX\V8\Object\ReflectionObject($instance));
    $environment->run($script);

    return $environment->get('response');

}

// Define a class that we'll pass in and out of php-v8.
class Foo {

    public $from = "PHP";

    function bar() {
        return "bar from Foo";
    }

}

// Our first script.
$script = <<<JS
response = fooInstance;
JS;

// This will pass an instance of Foo through php-v8 and provide us an ObjectWrapper in return.
// **We'd like it to return an instance of Foo so that we can use it again, and pass it through php-v8 again later on.**
$fooPassedThrough = execJS($script, new Foo());

// We can still execute a method, but it must be via the ObjectWrapper methods.
var_dump(
    $fooPassedThrough->get('bar')()
);

echo "\n";

// ->toNative() is closer, but it returns stdClass rather than an instance of class Foo.
// Also, you'll see that it doesn't recognise functions.
// $fooPassedThrough->toNative()->bar should be a function, but it is just a stdClass.
var_dump(
    $fooPassedThrough->toNative()
);

echo "\n";

// Here, we pass the result of the first pass through php-v8, back into php-v8
// showing that it can't consume objects again.
var_dump(
    execJS($script, $fooPassedThrough)->get('bar')()
);
```

We'd really like to be able to pass in an instance of `Foo`, and get one back so that we could continue to use it natively within PHP (i.e. without using the `ObjectWrapper` methods) and then pass it back through php-v8 again.

Is that something you think you is doable?

**Comment by chriskapp** [comment]
Hi, mhh so the problem with your case is that the object wrapper has no 
reference to the class "Foo" because we only pass the methods of the object as 
callbacks to v8. If I undestand this case correctly the best solution is 
probably to simply save the Foo instance some where and use it later on. Changes
in the javascript code should be reflected on your instance since the callbacks 
refer to the same object.
